Remove duplicate currency in EquitySummaryByReportDateInBase
This was added in 27d364e, and it's making tests fail:

```
Run mypy ibflex tests
...
ibflex/Types.py:471: error: Name "currency" already defined on line 386  [no-redef]
```